name: Web CI

on:
  push:
    paths:
      - 'web/**'
      - '!web/doctor-portal/**'
  pull_request:
    paths:
      - 'web/**'
      - '!web/doctor-portal/**'

jobs:
  web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build
